# Generated by Django 4.1.2 on 2022-11-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_status_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='count',
            new_name='quantity',
        ),
    ]
