# Generated by Django 4.1.2 on 2022-11-21 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_count_purchases_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+7?1?\\d{8,14}$')], verbose_name='Номер телефона'),
        ),
    ]
