# Generated by Django 4.1.2 on 2022-11-27 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orders_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^((\\+7|7|8)+([0-9]){10})$')], verbose_name='Номер телефона'),
        ),
    ]
