# Generated by Django 4.1.2 on 2022-12-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orders_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kinds',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={},
        ),
        migrations.AlterModelOptions(
            name='сategories',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='purchases',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders', verbose_name='Карзина'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products', verbose_name='Товар'),
        ),
    ]
