# Generated by Django 4.1.2 on 2023-02-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_account_options_alter_kinds_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders', verbose_name='Корзина'),
        ),
    ]
