# Generated by Django 4.1.2 on 2022-11-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_players_id_alter_tournaments_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='main/img/MembersAE', verbose_name='Эмблема')),
                ('q_we', models.BooleanField(verbose_name='Наша ли команда?')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
