# Generated by Django 4.1.2 on 2022-11-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='q_we',
            field=models.BooleanField(default=False, verbose_name='Наша ли команда?'),
        ),
    ]
