# Generated by Django 4.1.2 on 2022-11-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_members_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало турнира')),
                ('end_date', models.DateField(null=True, verbose_name='Окончание турнира')),
                ('update_date', models.DateField(null=True, verbose_name='Обновление данных таблицы')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tournaments', verbose_name='Турнир')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения матча')),
                ('stage', models.CharField(max_length=30, verbose_name='Стадия')),
                ('home_goals', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Голы домашней комадны')),
                ('away_goals', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Голы домашней комадны')),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='main.members', verbose_name='Гостевая команда')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='main.members', verbose_name='Домашняя команда')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tables')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
