# Generated by Django 4.1.2 on 2022-11-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tables_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='link_vk',
            field=models.CharField(max_length=100, null=True, verbose_name='Ссылка на вк'),
        ),
        migrations.AddField(
            model_name='players',
            name='link_vk',
            field=models.CharField(max_length=100, null=True, verbose_name='Ссылка на вк'),
        ),
        migrations.AlterField(
            model_name='players',
            name='photo',
            field=models.ImageField(null=True, upload_to='main/img/PlayersAE', verbose_name='Фото'),
        ),
    ]
