# Generated by Django 4.1.2 on 2022-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_matches_link_vk_players_link_vk_alter_players_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablesView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название команды')),
                ('count_games', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='Игры')),
                ('wins', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='Победы')),
                ('draws', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='Ничьи')),
                ('loses', models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='Поражения')),
                ('goal_for', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Забитые голы')),
                ('goal_against', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Пропущенные голы')),
                ('goal_difference', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Разница мячей')),
                ('pts', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Очки')),
                ('table_id', models.PositiveBigIntegerField(null=True, verbose_name='Турнир')),
                ('q_we', models.BooleanField(default=False, verbose_name='Наша ли команда?')),
            ],
            options={
                'verbose_name': 'Вертуальная таблица',
                'verbose_name_plural': 'Вертуальные таблицы',
                'db_table': 'table_tournaments',
                'managed': False,
            },
        ),
    ]
