# Generated by Django 4.1.2 on 2022-12-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tablesview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tablesview',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tournaments',
            options={},
        ),
        migrations.AlterField(
            model_name='tables',
            name='tournament',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.tournaments', verbose_name='Турнир'),
        ),
    ]
