# Generated by Django 4.1.2 on 2022-12-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_matches_options_alter_members_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='main.members', verbose_name='Гостевая команда'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='main.members', verbose_name='Домашняя команда'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tables'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tournaments', verbose_name='Турнир'),
        ),
    ]
