# Generated by Django 4.1.2 on 2023-02-03 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_alter_matches_away_team_alter_matches_home_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Загаловок')),
                ('short_description', models.CharField(max_length=256, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('img', models.ImageField(upload_to='main/img/NewsAE', verbose_name='Картинка к посту')),
                ('date_time', models.DateTimeField(null=True, verbose_name='Дата и время публикации')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Копирайтер')),
            ],
        ),
    ]
