# Generated by Django 4.1.2 on 2023-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(default='04-02-2023 19:19', null=True, verbose_name='Дата и время публикации'),
        ),
    ]
