# Generated by Django 4.1.2 on 2023-02-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации'),
        ),
    ]
