# Generated by Django 4.1.2 on 2023-02-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_news_options_alter_news_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
    ]
