# Generated by Django 4.1.2 on 2023-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Игровой номер')),
                ('photo', models.ImageField(null=True, upload_to='main/img/PlayersAE', verbose_name='Фото')),
                ('characteristic', models.TextField(null=True, verbose_name='Характеристика')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('signed', models.DateField(verbose_name='Присоединился к команде')),
                ('out', models.DateField(null=True, verbose_name='Ушёл')),
                ('link_vk', models.CharField(max_length=100, null=True, verbose_name='Ссылка на вк')),
            ],
        ),
    ]
