# Generated by Django 4.1.2 on 2023-02-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='players',
            name='last_name',
            field=models.CharField(default='kek', max_length=20, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
