# Generated by Django 4.1.2 on 2023-02-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_name_players_first_name_players_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
    ]
