# Generated by Django 4.1.2 on 2023-02-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_players_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(null=True, verbose_name='Кол-во голов')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.matches', verbose_name='Матч')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.players', verbose_name='Игрок')),
            ],
        ),
    ]
