# Generated by Django 4.1.2 on 2023-02-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_scoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('date', models.DateField(verbose_name='Дата проведения матча')),
                ('stage', models.CharField(max_length=30, verbose_name='Стадия')),
                ('home_goals', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Голы домашней комадны')),
                ('away_goals', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Голы домашней комадны')),
                ('link_vk', models.CharField(max_length=100, null=True, verbose_name='Ссылка на вк')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Naway_team', to='main.members', verbose_name='Гостевая команда')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nhome_team', to='main.members', verbose_name='Домашняя команда')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tables')),
            ],
        ),
    ]
