# Generated by Django 4.1.2 on 2023-02-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_newmatches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='table',
            new_name='table_tournament',
        ),
        migrations.RenameField(
            model_name='newmatches',
            old_name='table',
            new_name='table_tournament',
        ),
    ]
