# Generated by Django 4.1.2 on 2023-02-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_table_matches_table_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoring',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.newmatches', verbose_name='Матч'),
        ),
        migrations.DeleteModel(
            name='Matches',
        ),
    ]
