# Generated by Django 4.1.2 on 2023-02-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_scoring_match_delete_matches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewMatches',
            new_name='Matches',
        ),
    ]
