# Generated by Django 4.1.2 on 2023-02-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_newmatches_matches'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablesview',
            table='table_tournament',
        ),
    ]
