# Generated by Django 4.1.2 on 2023-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_tablesview_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publisher',
            field=models.CharField(default='Василий Пипуткин', max_length=30, verbose_name='Копирайтер'),
            preserve_default=False,
        ),
    ]
