# Generated by Django 4.1.2 on 2023-05-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_matchevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchEvent',
        ),
    ]
