# Generated by Django 4.1.2 on 2023-05-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_matchevent_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало трансляции')),
                ('pause', models.DateTimeField(verbose_name='Перерыв трансляции')),
                ('end', models.DateTimeField(verbose_name='Конец трансляции')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.matches')),
            ],
        ),
    ]
