# Generated by Django 4.1.2 on 2023-05-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_transmatch_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmatch',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='Конец трансляции'),
        ),
        migrations.AlterField(
            model_name='transmatch',
            name='pause',
            field=models.DateTimeField(null=True, verbose_name='Перерыв трансляции'),
        ),
        migrations.AlterField(
            model_name='transmatch',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='Начало трансляции'),
        ),
    ]
