# Generated by Django 4.1.2 on 2023-05-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_transmatch_end_alter_transmatch_pause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmatch',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.matches'),
        ),
    ]
