# Generated by Django 4.1.2 on 2023-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_transmatch_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmatch',
            name='start',
        ),
        migrations.AddField(
            model_name='transmatch',
            name='start_1',
            field=models.DateTimeField(null=True, verbose_name='Начало первого тайма'),
        ),
        migrations.AddField(
            model_name='transmatch',
            name='start_2',
            field=models.DateTimeField(null=True, verbose_name='Начало второго тайма'),
        ),
        migrations.AlterField(
            model_name='transmatch',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='Конец матча'),
        ),
        migrations.AlterField(
            model_name='transmatch',
            name='pause',
            field=models.DateTimeField(null=True, verbose_name='Перерыв'),
        ),
    ]
