# Generated by Django 4.1.2 on 2023-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_transmatch_start_transmatch_start_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmatch',
            name='end',
            field=models.TimeField(null=True, verbose_name='Конец матча'),
        ),
        migrations.AlterField(
            model_name='transmatch',
            name='pause',
            field=models.TimeField(null=True, verbose_name='Перерыв'),
        ),
        migrations.AlterField(
            model_name='transmatch',
            name='start_1',
            field=models.TimeField(null=True, verbose_name='Начало первого тайма'),
        ),
        migrations.AlterField(
            model_name='transmatch',
            name='start_2',
            field=models.TimeField(null=True, verbose_name='Начало второго тайма'),
        ),
    ]
