# Generated by Django 4.1.2 on 2023-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_transmatch_end_alter_transmatch_pause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='timestamp',
            field=models.CharField(max_length=5),
        ),
    ]
