# Generated by Django 4.1.2 on 2023-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_matchevent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='timestamp',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
