# Generated by Django 4.1.2 on 2023-05-23 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_matchevent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='data_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
