# Generated by Django 4.1.2 on 2023-06-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_matchevent_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoring',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во голов'),
        ),
    ]
