# Generated by Django 4.1.2 on 2023-06-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_scoring_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchevent',
            name='match',
        ),
        migrations.AddField(
            model_name='matchevent',
            name='trans',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.transmatch'),
            preserve_default=False,
        ),
    ]
