# Generated by Django 4.1.2 on 2023-07-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_matchevent_match_matchevent_trans'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGamesPlayers',
            fields=[
                ('id', models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.PositiveIntegerField(verbose_name='Игры')),
                ('goals', models.PositiveIntegerField(verbose_name='Голы')),
            ],
            options={
                'db_table': 'all_games_players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TourGamesPlayers',
            fields=[
                ('id', models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.PositiveIntegerField(verbose_name='Игры')),
                ('goals', models.PositiveIntegerField(verbose_name='Голы')),
            ],
            options={
                'db_table': 'tour_games_players',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='matches',
            name='away_goals',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Голы гостевой комадны'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateField(verbose_name='Дата матча'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_goals',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Голы домашней комадны'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='link_vk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на вк'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='table_tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tables', verbose_name='Турнир'),
        ),
        migrations.AlterField(
            model_name='players',
            name='characteristic',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='players',
            name='link_vk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на вк'),
        ),
        migrations.AlterField(
            model_name='players',
            name='out',
            field=models.DateField(blank=True, null=True, verbose_name='Ушёл'),
        ),
        migrations.AlterField(
            model_name='players',
            name='photo',
            field=models.ImageField(blank=True, default='main/img/PlayersAE/NoPhoto.png', null=True, upload_to='main/img/PlayersAE', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='players',
            name='signed',
            field=models.DateField(verbose_name='Присоединился'),
        ),
        migrations.AlterField(
            model_name='scoring',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Кол-во голов'),
        ),
    ]
