# Generated by Django 4.1.2 on 2023-07-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_allgamesplayers_tourgamesplayers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allgamesplayers',
            options={'managed': True},
        ),
    ]
