# Generated by Django 4.1.2 on 2023-07-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_allgamesplayers_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoring',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.players', verbose_name='Игрок'),
        ),
    ]
